CREATE TABLE IF NOT EXISTS users
(
    id    INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                         NOT NULL,
    email VARCHAR(255)                         NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(500)                            NOT NULL,
    available   BOOLEAN,
    owner_id    INT                                     NOT NULL,
    CONSTRAINT PK_ITEM PRIMARY KEY (item_id),
    CONSTRAINT FK_ITEM_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    start      TIMESTAMP WITH TIME ZONE NOT NULL,
    finish     TIMESTAMP WITH TIME ZONE NOT NULL,
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booker_id  INT                                     NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    status     VARCHAR(20)                             NOT NULL,
    CONSTRAINT PK_BOOKING PRIMARY KEY (booking_id),
    CONSTRAINT FK_BOOKING_ON_OWNER FOREIGN KEY (booker_id) REFERENCES users (id),
    CONSTRAINT FK_BOOKING_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (item_id)
);

CREATE TABLE IF NOT EXISTS comments(
    comment_id BIGINT NOT NULL PRIMARY KEY ,
    content VARCHAR
);

